### ISSUE TITLE
About popup on released apk trimmed

### ISSUE THREAD

**Issue by kaustubhhiware** [vigzmv/what_the_thing#5]
The popup seems to be trimmed as in the attached image. Not a big issue, but wanted you to note. Great project by the way :smile: 

![](https://lh3.googleusercontent.com/4mOcZ2Utu8HAAUOy_VzWSfxxVNN1dBVbS_Ou4O8eoDyiEhiB1p3-RHuZjp6UJABbA19WKSmnAq-SGUCBvq_srb0kbss=s341)

**Comment by vigzmv** [comment]
Thanks for pointing this out. It's because I wasn't sure how to work with density-independent pixels. Will fix this.

**Comment by vigzmv** [comment]
Fixed in #6
